### ISSUE TITLE
Create Django workflow

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#39]
1. Create a .github/workflows/django.yml file: Define your workflow in this file.
2. Define your jobs:
  - Install dependencies: Use pip to install your Django project’s dependencies.
  - Run tests: Execute your test suite using a test runner like pytest or Django's built-in test framework.
  - Linting: Optionally, run linters like flake8 to ensure your code follows best practices.

 ```yaml
name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      # Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies, including testing and coverage tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          # Install linting, formatting, and coverage tools
          pip install flake8 black

      # Step 4: Run linters
      - name: Run Flake8 (Linting)
        run: |
          flake8 .
      - name: Run Black (Formatting Check)
        run: |
          black --check .

      # Step 5: Set up the SQLite database
      - name: Set up SQLite database
        run: |
          python manage.py migrate  # Create the SQLite database with migrations

      # Step 6: Run tests
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: "my_project.settings.ci"  # Point to CI settings
        run: |
          python manage.py test
```
